name: Sync Discord Messages

permissions: write-all

on:
  push:
    branches:
      - main
    paths-ignore:
      - "state/**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: |
          bun install

      # STAGING
      - name: "sync messages for staging"
        run: |
          bun run useful-guides.ts
          bun run service-messages.ts
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          ENVIRONMENT: staging
      - name: staging state dump
        run: |
          echo "======== service-messages:"
          cat state/staging/service-messages.json
          echo "======== useful-guides:"
          cat state/staging/useful-guides.json

      # PRODUCTION
      - name: "sync messages for production"
        run: |
          bun run useful-guides.ts
          bun run service-messages.ts
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          ENVIRONMENT: production
      - name: production state dump
        run: |
          echo "======== service-messages:"
          cat state/production/service-messages.json
          echo "======== useful-guides:"
          cat state/production/useful-guides.json

      # COMMIT
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add state
          git diff --quiet && git diff --staged --quiet || git commit -m "[ci] sync state"
          git push
